language: cpp
compiler: gcc
sudo: require
dist: trusty

install:
  - sudo apt-get -y install libdevil-dev libtool libfontconfig1-dev clang libelf-dev freeglut3 freeglut3-dev gcc-avr avr-libc gcc make git libcairo2-dev # libtool-bin

script:
  - make -I shared/libc3/
  - export LD_LIBRARY_PATH=$(find . -type f -name '*.so*' -exec dirname {} \; | sort | uniq):$LD_LIBRARY_PATH
  - mkdir -p appdir/usr/bin ; cp ./obj-x86_64-linux-gnu/reprap.elf appdir/usr/bin/simreprap ; strip appdir/usr/bin/simreprap
  - mkdir -p appdir/usr/share/applications/ ; cp simreprap.desktop appdir/usr/share/applications/
  - mkdir -p appdir/usr/share/icons/hicolor/apps ; touch appdir/usr/share/icons/hicolor/apps/simreprap.svg
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  # export VERSION=... # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh simreprap*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
